services:
  app:
    build:
      context: .
      args:
        NEXT_PUBLIC_BASE_PATH: /apps/infinite-canvas
    image: infinite-canvas:oss-sso-local
    pull_policy: never
    container_name: infinite-canvas
    env_file:
      - .env
    expose:
      - "3000"
    networks:
      portal_gateway:
        aliases:
          - infinite-canvas-app
      internal_tools_database: {}
    restart: unless-stopped
    volumes:
      - ./data/media:/app/data/media

networks:
  portal_gateway:
    external: true
    name: portal_gateway
  internal_tools_database:
    external: true
    name: internal_tools_database
